# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('job_url', models.CharField(max_length=200)),
                ('job_dec', models.TextField()),
            ],
        ),
    ]
