# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-26 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20171226_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='job_dec',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
