# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_java_job_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenrnType', models.CharField(max_length=30)),
                ('learnURL', models.CharField(max_length=200)),
                ('learnLabel', models.CharField(max_length=100, null=True)),
                ('webName', models.CharField(max_length=30)),
            ],
        ),
    ]
