# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_java_job_salaryone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_job',
            name='salaryOne',
            field=models.IntegerField(default=1000),
        ),
    ]
