# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20171230_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_job',
            name='salaryOne',
            field=models.FloatField(default=1.0),
        ),
    ]
