# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-30 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20171230_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_job',
            name='positionId',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
