# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20171230_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='isGetDetail',
            field=models.BooleanField(default=False),
        ),
    ]
