# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-02 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_joblist_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='keyWord',
            field=models.TextField(null=True),
        ),
    ]
