# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_joblist_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='java_job',
            name='workYearAvr',
            field=models.FloatField(default=0.0),
        ),
    ]
